In [1]:
import pandas as pd
import numpy as np
from numpy import random as rnd
pd.set_option('display.max_columns', None)

In [2]:
column_names = ['id_paciente','v27Histologia_2016','v29Estadif_TNM_2016','v31Prueba_HER2_2016','v33Resultado_HER2_2016','v40objetivo_tto_2016','v45recibioquimio_2016','v46Fases_QT_2016','v53Cant_antineoplasic_2016','v60motivofinaliz_2016','v70quimiointrat_fin_2016','v90Tipo_RT_periodo_2016','v111cx_reconst_2016','v118Fecha_val_psiqu_2016','v123Soporte_nutric_2016','v124Terap_complem_2016','v126rdomanejocorte_2016','v127edovitalcorte_2016','v132causademuerte_2016','diagnostico_reportado_inicio_1er_ciclo','dias_informe_histopatologia_primera_consulta','dias_diagnostico_reportado_muestra_histopatologica','dias_diagnostico_reportado_primera_consulta','primera_consulta_ingreso_institucion','diagnostico_reportado_otro_cancer_primario','finalizacion_primer_esquema_diagnostico_reportado','inicio_ultimo_esquema_diagnostico_reportado','finalizacion_ultimo_esquema_diagnostico_reportado','finalizacion_ultimo_esquema_inicio_ultimo_esquema','primera_cirugia_finalizacion_ultimo_esquema','ultima_cirugia_primera_cirugia','inicio_esquema_radio_diagnostico_reportado','final_esquema_radio_inicio_esquema_radio','incio_ultimo_esquema_radio_final_primer_esquema_radio','final_ultimo_esquema_radio_incio_ultimo_esquema_radio','cirugia_reconstructiva_diagnosticoreportado','primera_consulta_paleativodiagnostico_reportado','primera_consulta_psiquiatriadiagnosticoreportado','primeraconsulta_nutricion_diagnostico_reportado','fecha_muerte_diagnostico_reportado','anio']

In [3]:
df_cac = pd.DataFrame(columns = column_names)

In [4]:
a = list(range(1,22))
b = [55,98,99]
a.extend(b)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 55, 98, 99]


In [5]:
data = np.random.randint(5,30,size=27000)
df_cac = pd.DataFrame(data, columns=['id_paciente'])
a = list(range(1,22))
b = [55,98,99]
a.extend(b)
x = rnd.choice(a, size= 27000)

print(x)

[13 17 20 ...  1  5  4]


In [6]:
a = list(range(0,0))
a

[]

In [7]:
def generate_data(min, max, lista):
    a = list(range(min,max))
    b = lista
    a.extend(b)
    data = rnd.choice(a, size= 12000)
    return data
    

In [8]:
test = generate_data(1,22,[])
print(test)

[ 1 10  5 ...  6  4 14]


In [9]:
generate_data(0,0,[0,55,98])

array([ 0,  0,  0, ..., 55,  0, 55])

In [10]:
generate_data(0,0,['1845-01-01','1846-01-01'])

array(['1845-01-01', '1845-01-01', '1845-01-01', ..., '1846-01-01',
       '1845-01-01', '1845-01-01'], dtype='<U10')

In [11]:
generate_data(,325,[])

SyntaxError: invalid syntax (<ipython-input-11-930142993b58>, line 1)

In [12]:
df_cac

id_paciente
0               27
1               18
2               24
3                6
4               16
...            ...
26995           16
26996           25
26997           11
26998           17
26999            7

[27000 rows x 1 columns]

In [13]:
import random

In [14]:
data = random.sample(range(100000), 12000)
df_cac = pd.DataFrame(data, columns=['id_paciente'])
df_cac['v27Histologia'] = generate_data(1,24,[55,98,99])
df_cac['v29Estadif_TNM'] = generate_data(1,25,[55,93,98,99])
df_cac['v31Prueba_HER2'] = generate_data(1,2,[55,97,98,99])
df_cac['v33Resultado_HER2'] = generate_data(1,4,[55,97,98,99])
df_cac['v40objetivo_tto'] = generate_data(1,2,[55,99])
df_cac['v45recibioquimio'] = generate_data(1,2,[55,98])
df_cac['v46Fases_QT'] = generate_data(0,0,[0,55,98])
df_cac['v53Cant_antineoplasic'] = generate_data(0,0,[98,99])
df_cac['v60motivofinaliz'] = generate_data(1,28,[55,98])
df_cac['v70quimiointrat_fin'] = generate_data(1,2,[98])
df_cac['v90Tipo_RT_periodo'] = generate_data(1,7,[55,98])
df_cac['v111cx_reconst'] = generate_data(1,2,[55,98])
df_cac['v118Fecha_val_psiqu'] = generate_data(0,0,['1845-01-01','1846-01-01'])
df_cac['v123Soporte_nutric'] = generate_data(1,4,[55,98])
df_cac['v124Terap_complem'] = generate_data(1,8,[55,98])
df_cac['v126rdomanejocorte'] = generate_data(1,7,[55,97,98,88])
df_cac['v127edovitalcorte'] = generate_data(1,2,[55,99])
df_cac['v132causademuerte'] = generate_data(1,24,[55,98])

df_cac['diagnostico_reportado_inicio_1er_ciclo'] = generate_data(46,325,[])
df_cac['dias_informe_histopatologia_primera_consulta'] = generate_data(33,357,[])
df_cac['dias_diagnostico_reportado_muestra_histopatologica'] = generate_data(15,156,[])
df_cac['dias_diagnostico_reportado_primera_consulta'] = generate_data(19,337,[])
df_cac['primera_consulta_ingreso_institucion'] = generate_data(4,66,[])
#df_cac['diagnostico_reportado_otro_cancer_primario'] = generate_data(1,24,[])
df_cac['finalizacion_primer_esquema_diagnostico_reportado'] = generate_data(57,350,[])
df_cac['inicio_ultimo_esquema_diagnostico_reportado'] = generate_data(133,351,[])
df_cac['finalizacion_ultimo_esquema_diagnostico_reportado'] = generate_data(92,361,[])
df_cac['finalizacion_ultimo_esquema_inicio_ultimo_esquema'] = generate_data(0,33,[])
df_cac['primera_cirugia_finalizacion_ultimo_esquema'] = generate_data(0,24,[])
df_cac['ultima_cirugia_primera_cirugia'] = generate_data(0,24,[])
df_cac['inicio_esquema_radio_diagnostico_reportado'] = generate_data(0,349,[])
df_cac['final_esquema_radio_inicio_esquema_radio'] = generate_data(1,24,[])
df_cac['incio_ultimo_esquema_radio_final_primer_esquema_radio'] = generate_data(1,24,[])
df_cac['final_ultimo_esquema_radio_incio_ultimo_esquema_radio'] = generate_data(1,24,[])
df_cac['cirugia_reconstructiva_diagnosticoreportado'] = generate_data(0,352,[])
df_cac['primera_consulta_psiquiatriadiagnosticoreportado'] = generate_data(0,289,[])
df_cac['primeraconsulta_nutricion_diagnostico_reportado'] = generate_data(0,338,[])
df_cac['primera_consulta_paleativodiagnostico_reportado'] = generate_data(0,327,[])
df_cac['fecha_muerte_diagnostico_reportado'] = generate_data(150,350,[])
df_cac['anio'] = generate_data(0,0,[2015,2016,2017,2018,2019,2020])

df_cac


id_paciente  v27Histologia  v29Estadif_TNM  v31Prueba_HER2  \
0            23507             12               7               1   
1            14132             18               1              97   
2            80443             23              19              98   
3            53329             11              20               1   
4            96744             98               7              97   
...            ...            ...             ...             ...   
11995        27671              9               4              99   
11996        55125             10              15              99   
11997        73228             17              98               1   
11998        72027              5              14              98   
11999        18261             22               8              99   

       v33Resultado_HER2  v40objetivo_tto  v45recibioquimio  v46Fases_QT  \
0                      2               99                98           98   
1                     55               55                98            0   
2                     55               99                 1            0   
3                      2                1                98            0   
4                     98               55                 1           55   
...                  ...              ...               ...          ...   
11995                 97               55                98            0   
11996                 55               99                55            0   
11997                  3                1                55           98   
11998                 99                1                98           55   
11999                 97                1                 1            0   

       v53Cant_antineoplasic  v60motivofinaliz  v70quimiointrat_fin  \
0                         98                 8                   98   
1                         99                10                   98   
2                         98                 3                    1   
3                         99                20                   98   
4                         99                 3                    1   
...                      ...               ...                  ...   
11995                     98                 4                    1   
11996                     99                20                   98   
11997                     98                 9                    1   
11998                     99                18                   98   
11999                     98                11                    1   

       v90Tipo_RT_periodo  v111cx_reconst v118Fecha_val_psiqu  \
0                       1              55          1845-01-01   
1                      55              55          1845-01-01   
2                      55              98          1845-01-01   
3                       5               1          1846-01-01   
4                       5               1          1845-01-01   
...                   ...             ...                 ...   
11995                   5              98          1845-01-01   
11996                  55               1          1845-01-01   
11997                  98               1          1846-01-01   
11998                   2              55          1846-01-01   
11999                   4              55          1845-01-01   

       v123Soporte_nutric  v124Terap_complem  v126rdomanejocorte  \
0                       3                  7                   5   
1                       2                  4                   5   
2                       1                 98                   6   
3                       2                  5                   1   
4                       1                  3                  97   
...                   ...                ...                 ...   
11995                  55                  5                  97   
11996                   3                  4                   3   
11997              

In [15]:
df_cac.to_csv('df_cac.csv', index=False)

In [ ]:
lista = df_cac.columns
lista

In [ ]:
fig = px.histogram(df_cac, y="id_paciente", x=['diagnostico_reportado_inicio_1er_ciclo',
       'dias_informe_histopatologia_primera_consulta',
       'dias_diagnostico_reportado_muestra_histopatologica',
       'dias_diagnostico_reportado_primera_consulta',
       'primera_consulta_ingreso_institucion',
       'finalizacion_primer_esquema_diagnostico_reportado',
       'inicio_ultimo_esquema_diagnostico_reportado',
       'finalizacion_ultimo_esquema_diagnostico_reportado',
       'finalizacion_ultimo_esquema_inicio_ultimo_esquema',
       'primera_cirugia_finalizacion_ultimo_esquema',
       'ultima_cirugia_primera_cirugia',
       'inicio_esquema_radio_diagnostico_reportado',
       'final_esquema_radio_inicio_esquema_radio',
       'incio_ultimo_esquema_radio_final_primer_esquema_radio',
       'final_ultimo_esquema_radio_incio_ultimo_esquema_radio',
       'cirugia_reconstructiva_diagnosticoreportado',
       'primera_consulta_psiquiatriadiagnosticoreportado',
       'primeraconsulta_nutricion_diagnostico_reportado',
       'primera_consulta_paleativodiagnostico_reportado',
       'fecha_muerte_diagnostico_reportado'], orientation='h')
fig.show()

In [ ]:
df_cac['v45recibioquimio'][0]


In [ ]:
import plotly.express as px
px.histogram(df_cac, x=df_cac['v45recibioquimio'], labels={'x':'v45recibioquimio', 'y':'count'})

In [ ]:
for indicador in df_cac.columns:
    fig = px.histogram(df_cac, x=df_cac[indicador], labels={
        'x': indicador, 'y': 'count'})
    fig.show()

In [ ]:
import plotly.express as px
fig = px.bar(df_cac, x='v45recibioquimio', y=len(df_cac[df_cac["v45recibioquimio"]]), color='v45recibioquimio')
fig.show()

In [ ]:
data = np.random.randint(5,30,size=27000)
df_cac['v29Estadif_TNM_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v31Prueba_HER2_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v33Resultado_HER2_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v40objetivo_tto_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v45recibioquimio_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v46Fases_QT_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v53Cant_antineoplasic_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v60motivofinaliz_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v70quimiointrat_fin_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v90Tipo_RT_periodo_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v111cx_reconst_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v118Fecha_val_psiqu_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v123Soporte_nutric_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v124Terap_complem_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v126rdomanejocorte_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v127edovitalcorte_2016'] = data
data = np.random.randint(5,30,size=27000)
df_cac['v132causademuerte_2016'] = data

In [ ]:
df_cac.columns

In [ ]:
df = pd.DataFrame(np.random.randint(0,100,size=(15, 4)), columns=list('ABCD'))

In [ ]:
df